# docker-compose.yml
version: '3'

services:
  app:
    build: .
    container_name: myapp
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
