"""Добавил пароли

Revision ID: 1ea806fc8954
Revises: a486e7aec67b
Create Date: 2024-04-24 20:25:01.111092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea806fc8954'
down_revision = 'a486e7aec67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('p_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('check_password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_column('check_password')
        batch_op.drop_column('password')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('p_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
