"""Add Accept

Revision ID: 3d33b32902bc
Revises: 613f45eec468
Create Date: 2024-06-24 17:21:24.567456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d33b32902bc'
down_revision = '613f45eec468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accept',
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('patronymic', sa.String(length=20), nullable=False),
    sa.Column('menu', sa.String(length=20), nullable=False),
    sa.Column('music', sa.String(length=20), nullable=False),
    sa.Column('hist', sa.String(length=20), nullable=False),
    sa.Column('fact', sa.String(length=20), nullable=False),
    sa.Column('surprise', sa.String(length=20), nullable=False),
    sa.Column('question', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('guest_id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint('admin_p_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_unique_constraint('admin_p_number_key', ['p_number'])

    op.drop_table('accept')
    # ### end Alembic commands ###
