"""Add Admin

Revision ID: 613f45eec468
Revises: f853d5f54f24
Create Date: 2024-06-23 23:05:25.973285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613f45eec468'
down_revision = 'f853d5f54f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('p_number', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['p_number'], ['guest.p_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('p_number')
    )
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_constraint('guest_password_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.create_unique_constraint('guest_password_key', ['password'])

    op.drop_table('admin')
    # ### end Alembic commands ###
