"""Добавил параметр уникальных значений

Revision ID: f853d5f54f24
Revises: f2bb57deee01
Create Date: 2024-05-22 19:16:42.682563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f853d5f54f24'
down_revision = 'f2bb57deee01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['password'])
        batch_op.create_unique_constraint(None, ['s_n'])
        batch_op.create_unique_constraint(None, ['p_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
